config/routes.rb
Rails.application.routes.draw do
  resources :procesos_maquinas
  resources :habilitar_rol_maquinas
  resources :programaciones_op_maquinas
  resources :variables_estandar
  resources :contenedores_de_acabados
  resources :acabados
  resources :lugares_despachos
  resources :nombres_facturaciones
  resources :contenedores_de_maquinas
  resources :linea_de_colores
  resources :materiales
  resources :contenedores_de_ordenes
  resources :contenedor_de_remisiones
  resources :facturas
  resources :transiciones
  resources :desarrollos_de_tintas
  resources :ordenes_produccion
  resources :compromisos_de_entrega
  resources :tintas_fop_retiro
  resources :tintas_fop_tiro
  resources :formulas_tinta
  resources :tintas_formuladas
  resources :tintas
  resources :mallas
  resources :formatos_op
  resources :formato_ops
  resources :meses
  resources :remisiones
  resources :facturas_despacho
  resources :tiempos_de_entregas
  resources :ordenes_de_produccion
  resources :despachos
  resources :pedidos
  resources :lineas_de_impresiones
  resources :contactos
  resources :clientes
  devise_for :users
  resources :users
  resources :roles
  resources :montajes
  resources :piezas
  resources :maquinas
  resources :lineas_productos
  resources :lineas_de_colores
  resources :piezas_a_decorar


  get 'produccion', to: 'pedidos#produccion', as: :produccion

  get 'entregas', to: 'pedidos#entregas', as: :entregas

  root :to => 'static_pages#home'

  get 'info_produccion', to: 'ordenes_de_produccion#info_produccion', as: :info_produccion

  post 'crearNuevaOrden', to: 'ordenes_de_produccion#crearNuevaOrden', as: :crearNuevaOrden

  get 'consultar_despacho/:id', to: 'pedidos#consultar_despacho', as: :consultar_despacho

  get 'info_despacho/:id', to: 'tiempos_de_entregas#info_despacho', as: :info_despacho

  get 'cambiar_estado/:id', to: 'pedidos#cambiar_estado', as: :cambiar_estado

  get 'cambiar_estado_a_Pedido/:id', to: 'pedidos#cambiar_estado_a_Pedido', as: :cambiar_estado_a_Pedido

  get 'genera_reporte_pedido', to: 'pedidos#genera_reporte_pedido', as: :genera_reporte_pedido


# resources :ordenes_de_produccion, :only => :none do
#      get :info_produccion
#  end


  resources :contactos, :only => :none do
      get :vista
  end

  post 'import_from_excel' => "clientes#import_from_excel"
  get 'vista_subir_excel', to: 'clientes#vista_subir_excel'
  post 'import_contactos_from_excel/:id' => "clientes#import_contactos_from_excel", as: :import_contactos_from_excel
  get 'contactos_subir_excel', to: 'clientes#contactos_subir_excel'

  get 'cambiar_proceso/:id', to: 'ordenes_produccion#cambiar_proceso', as: :cambiar_proceso
  get 'cambiar_estado_pantalla/:id', to: 'ordenes_produccion#cambiar_estado_pantalla', as: :cambiar_estado_pantalla
  get 'cambiar_estado_color/:id', to: 'ordenes_produccion#cambiar_estado_color', as: :cambiar_estado_color
  get 'cambiar_estado_corte_material/:id', to: 'ordenes_produccion#cambiar_estado_corte_material', as: :cambiar_estado_corte_material
  get 'cambiar_estado_impresion/:id', to: 'ordenes_produccion#cambiar_estado_impresion', as: :cambiar_estado_impresion
  get 'cambiar_estado_troquel/:id', to: 'ordenes_produccion#cambiar_estado_troquel', as: :cambiar_estado_troquel
  get 'cambiar_estado_acabados/:id', to: 'ordenes_produccion#cambiar_estado_acabados', as: :cambiar_estado_acabados
  get 'cambiar_habilitar_impresion/:id', to: 'ordenes_produccion#cambiar_habilitar_impresion', as: :cambiar_habilitar_impresion
  get 'cambiar_habilitar_acabado/:id', to: 'ordenes_produccion#cambiar_habilitar_acabado', as: :cambiar_habilitar_acabado

  get 'despacho_facturas', to: 'tiempos_de_entregas#despacho_facturas', as: :despacho_facturas
  get 'info_despacho_facturas/:id', to: 'tiempos_de_entregas#info_despacho_facturas', as: :info_despacho_facturas
  get 'anexar_num_factura/:id', to: 'tiempos_de_entregas#anexar_num_factura', as: :anexar_num_factura
  get 'consultar_factura', to: 'tiempos_de_entregas#consultar_factura', as: :consultar_factura
  get 'anexar_tiempo_de_entrega', to: 'tiempos_de_entregas#anexar_tiempo_de_entrega', as: :anexar_tiempo_de_entrega
  get 'ver_factura/:id', to: 'tiempos_de_entregas#ver_factura', as: :ver_factura
  get 'cerrar_pedido/:id', to: 'tiempos_de_entregas#cerrar_pedido', as: :cerrar_pedido
  get 'ordenes', to: 'pedidos#ordenes', as: :ordenes

  get 'buscar_fop/:id', to: 'montajes#buscar_fop', as: :buscar_fop

  get 'cargar_form_formato', to: 'ordenes_produccion#cargar_form_formato', as: :cargar_form_formato

  get 'cargar_form', to: 'ordenes_produccion#cargar_form', as: :cargar_form

  post 'import_fop_from_excel' => "formatos_op#import_fop_from_excel", as: :import_fop_from_excel

  post 'import_montaje_from_excel' => "montajes#import_montaje_from_excel", as: :import_montaje_from_excel


  post 'import__MP_from_excel' => "montajes#import__MP_from_excel", as: :import__MP_from_excel

  post 'import_tintas_from_excel' => "tintas#import_tintas_from_excel", as: :import_tintas_from_excel

  post 'import_tintas_formuladas_from_excel' => "tintas_formuladas#import_tintas_formuladas_from_excel", as: :import_tintas_formuladas_from_excel

  post 'import_formulaTintas_from_excel' => "formulas_tinta#import_formulaTintas_from_excel", as: :import_formulaTintas_from_excel

  post 'import_ordenes_produccion_from_excel' => "ordenes_produccion#import_ordenes_produccion_from_excel", as: :import_ordenes_produccion_from_excel

  get 'busquedaTintas', to: 'formulas_tinta#busquedaTintas', as: :busquedaTintas

  get 'busquedaTintasMontaje/:id', to: 'montajes#busquedaTintasMontaje', as: :busquedaTintasMontaje

  get 'select_buscar_montaje/:id', to: 'ordenes_produccion#select_buscar_montaje', as: :select_buscar_montaje

  get 'deshacer_envio/:id', to: 'compromisos_de_entrega#deshacer_envio', as: :deshacer_envio

  get 'produccion_pantallas', to: 'ordenes_produccion#produccion_pantallas', as: :produccion_pantallas
  get 'info_pantallas/:id', to: 'ordenes_produccion#info_pantallas', as: :info_pantallas
  get 'cerrar_pantalla/:id', to: 'ordenes_produccion#cerrar_pantalla', as: :cerrar_pantalla


  get 'produccion_coordinador', to: 'ordenes_produccion#produccion_coordinador', as: :produccion_coordinador
  get 'info_coordinador/:id', to: 'ordenes_produccion#info_coordinador', as: :info_coordinador
  get 'cerrar_materiales/:id', to: 'ordenes_produccion#cerrar_materiales', as: :cerrar_materiales

  get 'produccion_comercial', to: 'ordenes_produccion#produccion_comercial', as: :produccion_comercial

  get 'produccion_color', to: 'ordenes_produccion#produccion_color', as: :produccion_color
  get 'info_color/:id', to: 'ordenes_produccion#info_color', as: :info_color
  get 'cerrar_color/:id', to: 'ordenes_produccion#cerrar_color', as: :cerrar_color
  get 'info_factura/:id', to: 'facturas#info_factura', as: :info_factura

  get 'tintas_select/:id', to: 'montajes#tintas_select', as: :tintas_select


  get 'desarrollar_color/:id', to: 'ordenes_produccion#desarrollar_color', as: :desarrollar_color

  get 'crear_color/:id', to: 'tintas_formuladas#crear_color', as: :crear_color

  get 'desarrollar_tintas_tiro/:id', to: 'ordenes_produccion#desarrollar_tintas_tiro', as: :desarrollar_tintas_tiro

  get 'desarrollar_tintas_retiro/:id', to: 'ordenes_produccion#desarrollar_tintas_retiro', as: :desarrollar_tintas_retiro
  get 'desarrollar_factura/:id', to: 'facturas#desarrollar_factura', as: :desarrollar_factura

  get 'form_ordenes', to: 'montajes#form_ordenes', as: :form_ordenes


  get 'buscador_de_ordenes', to: 'ordenes_produccion#buscador_de_ordenes', as: :buscador_de_ordenes

  post 'buscador_de_ordenes_por_mes', to: 'ordenes_produccion#buscador_de_ordenes_por_mes', as: :buscador_de_ordenes_por_mes
  post 'buscador_de_ordenes_por_fecha', to: 'ordenes_produccion#buscador_de_ordenes_por_fecha', as: :buscador_de_ordenes_por_fecha

  post 'busquda_avanzada_produccion', to: 'ordenes_produccion#busquda_avanzada_produccion', as: :busquda_avanzada_produccion
  get 'cargar_select_advance_search', to: 'ordenes_produccion#cargar_select_advance_search', as: :cargar_select_advance_search

  get 'buscador_de_ordenes_despachos', to: 'compromisos_de_entrega#buscador_de_ordenes_despachos', as: :buscador_de_ordenes_despachos

  get 'buscador_de_fichas', to: 'montajes#buscador_de_fichas', as: :buscador_de_fichas

  get 'buscador_de_tintas', to: 'tintas#buscador_de_tintas', as: :buscador_de_tintas

  get 'buscador_de_tintas_formuladas', to: 'tintas_formuladas#buscador_de_tintas_formuladas', as: :buscador_de_tintas_formuladas

  post 'import_materiales_excel' => "materiales#import_materiales_excel", as: :import_materiales_excel

  get 'contactos_for_select/:id', to: 'montajes#contactos_for_select', as: :contactos_for_select

  get 'reporte_tinta/:id', to: 'ordenes_produccion#reporte_tinta', as: :reporte_tinta
  get 'open_modal_import', to: 'ordenes_produccion#open_modal_import', as: :open_modal_import

  get 'produccion_por_maquinas', to: 'maquinas#produccion_por_maquinas', as: :produccion_por_maquinas
  get 'consulta_por_maquinas/:id', to: 'maquinas#consulta_por_maquinas', as: :consulta_por_maquinas

  get 'detalles_produccion_maquina/:id', to: 'maquinas#detalles_produccion_maquina', as: :detalles_produccion_maquina

  get 'deshacer_programa_maquina/:id', to: 'programaciones_op_maquinas#deshacer_programa_maquina', as: :deshacer_programa_maquina
  get 'confirmar_impresion/:id', to: 'maquinas#confirmar_impresion', as: :confirmar_impresion


  get 'buscar_orden_maquina', to: 'maquinas#buscar_orden_maquina', as: :buscar_orden_maquina

  get 'programacion_maquinas_excel/:id', to: 'maquinas#programacion_maquinas_excel', as: :programacion_maquinas_excel

  get 'select_onchange_search', to: 'contactos#select_onchange_search', as: :select_onchange_search

  post 'blur_edit_machine', to: 'maquinas#blur_edit_machine', as: :blur_edit_machine

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]
#Clientes Excel
  def vista_subir_excel
    @user_id= current_user.id
  end



  def buscar_nombre_cliente
    data = params["data"]
    puts"===============#{data}================".blue
    estado = true
    comercial= "Comercial"
    gerente_comercial = "Gerente Comercial"
    @clientes = Cliente.where("nombre ILIKE ? AND estado = ?", "%"+data+"%", estado).order('nombre')
    @comerciales = User.joins(:rol).where('roles.cargo = ? OR roles.cargo = ?', comercial, gerente_comercial)

    respond_to do |format|
        format.js
    end
  end

  def import_from_excel

    file = params[:file]
    begin
      errores_o_true = Cliente.subir_excel(file)

      respond_to do |format|
        if errores_o_true == true
          format.html { redirect_to clientes_path, notice: 'Clientes Importados' }
          format.json { render :show, status: :created, location: @cliente }
        else
          @errores = errores_o_true
          format.html { render 'vista_subir_excel'}
        end
    end
    rescue Exception => e
      flash[:notice] = "Tipo de archivo no valido"
      redirect_to clientes_path
    end
  end

#Contactos Excel
def contactos_subir_excel

end



#validarCreacionDeCliente
def ValidarClienteBusquedad
  #code
  data = params['data']
  data = data.to_s.upcase
  puts "******************ESTA ES LA DATA: #{data}**********************".red
  val_estado = true
  @clientes = []
  @clientes= Cliente.where("nombre  = ? AND estado = ?", data, val_estado).order('nombre') if data.present?

  @validar = false
  @validar = true if @clientes.empty?
  respond_to do |format|
    format.js
  end
end

def import_contactos_from_excel
  @cliente = Cliente.find(params[:id])

  my_user_id = current_user.id
  file = params[:file]
  begin
    errores_o_true = Cliente.subir_excel_contactos(file, my_user_id, @cliente.id)

    respond_to do |format|
      if errores_o_true == true
        format.html { redirect_to @cliente, notice: 'Contactos Importados' }
        format.json { render :show, status: :created, location: @cliente }
      else
        @errores = errores_o_true
        format.html { render 'vista_subir_excel'}
      end
  end
  rescue Exception => e
    flash[:notice] = "Tipo de archivo no valido"
    redirect_to clientes_path
  end
end

  # GET /clientes
  # GET /clientes.json
  def index
    if current_user.rol.cargo == "Administrador"
      @clientes = Cliente.all.paginate(page: params[:page], per_page: 20).order('nombre').distinct
      comercial= "Comercial"
      gerente_comercial = "Gerente Comercial"
      @comerciales = User.joins(:rol).where('roles.cargo = ? OR roles.cargo = ?', comercial, gerente_comercial)

    elsif current_user.rol.cargo == "Comercial"
      @clientes = Cliente.joins(:contactos, :user).paginate(page: params[:page], per_page: 20).where("contactos.user_id=#{current_user.id}").order('nombre').distinct
      comercial= "Comercial"
      gerente_comercial = "Gerente Comercial"
      @comerciales = User.joins(:rol).where('roles.cargo = ? OR roles.cargo = ?', comercial, gerente_comercial)

    elsif current_user.rol.cargo == "Producción"
      val_estado = true
      @clientes = Cliente.all.paginate(page: params[:page], per_page: 20).where("estado =?",val_estado).order('nombre').distinct
      comercial= "Comercial"
      gerente_comercial = "Gerente Comercial"
      @comerciales = User.joins(:rol).where('roles.cargo = ? OR roles.cargo = ?', comercial, gerente_comercial)

    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    puts "==============="+@cliente.id.to_s+"======================"

  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
    @cliente.contactos.build
    @cliente.nombres_facturaciones.build
    @cliente.lugares_despachos.build
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = current_user.clientes.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to clientes_url, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to clientes_url, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :nit, :direccion, :telefono, :correo, :user_id, :estado,
      contactos_attributes: [:id,:_destroy,:nombre_contacto, :telefono, :celular, :correo, :cliente_id, :user_id,:estado],
      lugares_despachos_attributes:[:id,:_destroy,:cliente_id, :nombre, :direccion, :telefono],
      nombres_facturaciones_attributes:[:id,:_destroy,:cliente_id, :nombre, :direccion, :telefono]
    )
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/ValidarClienteBusquedad.js.erb
respuesta = "<%= @validar%>"



console.log(respuesta);


if (respuesta == "true") {

  $("#montaje_new_cliente").css("border", "1px solid #3c763d");
  $("#validar_cliente_nuevo").hide()


}else{

    $("#montaje_new_cliente").css("border", "1px solid #a94442");
    var mensaje = "<span>este cliente ya existe</span>"
    $("#validar_cliente_nuevo").html(mensaje)
    $("#validar_cliente_nuevo").show()

}

app/views/clientes/_lugar_despacho.html.erb
<tr>
  <td>
    <%= f.input :direccion %>
  </td>


  <td>
    <label for=""></label> <br>
    <%= f.input_field :_destroy, as: :hidden %>
    <%= link_to '<button type="button" class="btn btn-outline-danger btn_delete_contacto"><span><i class="ion-trash-a"></i></span></button>'.html_safe, '#', class: 'remove_lugar_despacho' %>
  </td>
</tr>

app/views/clientes/_respuesta_busqueda_clientes.html.erb
<% if @clientes.empty?%>

  <tr>
    <td colspan="8" >
      NO HAY REGISTROS CON ESE NOMBRE
    </td>
  </tr>

<%else%>
    <%   @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.nit %></td>
        <td><%= cliente.direccion %></td>
        <td><%= cliente.telefono %></td>
        <td><%= best_in_place cliente, :user_id,  :as => :select,
        :collection => @comerciales.map{|i| [i.id, i.nombre]}%></td>
        <td><%= link_to '<button class="btn btn-outline-primary"><span><i class="ion-person-stalker"></i></i></span></button>'.html_safe, cliente %></td>
        <td><%= link_to '<button class="btn btn-outline-warning"><span><i class="ion-paintbrush"></i></i></span></button>'.html_safe, edit_cliente_path(cliente) %></td>
        <td><%= link_to '<button class="btn btn-outline-danger"><span><i class="ion-trash-a"></i></i></span></button>'.html_safe, cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

<% end %>

app/views/clientes/buscar_nombre_cliente.js.erb
$("#agregar_busqueda").html('<%= j render 'respuesta_busqueda_clientes'%>')
$(".cont_oc").hide()

app/views/clientes/contactos_subir_excel.html.erb
<p id="notice"><%= notice %></p>

<% if @errores %>
  <% @errores.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<h1>Importar Contactos de Excel</h1>
 <%= form_tag import_contactos_from_excel_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import", :class=> "btn"%>
<% end %>
<h1><%=@user_id%></h1>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>
<%= link_to '<button type="button" class="btn btn-outline-primary">Listar Clientes</button>'.html_safe, clientes_path %>



<br>




<%= render 'form', cliente: @cliente %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>






<div class="my_card_pedidos_form">


      <div class="col-6">
        <h1>Clientes</h1>
      </div>

      <div class="col-3 offset-md-3">
        <%= link_to '<button type="button" class="btn btn-outline-dark float-xl-right">Registrar Cliente</button>'.html_safe, new_cliente_path %>
      </div>

</div>

<br>

<%= form_tag buscar_nombre_cliente_path, class: 'form-inline my_card_contactos_form form-inline',remote:true do%>

    <div class="col-6">

            <%= button_tag type: 'submit', class: "btn btn-primary input-group-btn form-control" do %>
              <span>Buscar Cliente... <i></i> </span>
            <%end%>
            <%= text_field_tag 'data', "",class:"form-control input-group"%>


      </div>

      <div class="col-3">
        <%= link_to '<button type="button" class="btn btn-outline-primary">Listar Clientes</button>'.html_safe, clientes_path %>
      </div>






<%end%>


<br>

<div class="pull-right cont_oc">
  <%= will_paginate @clientes, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Nit</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Vendedor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="agregar_busqueda">
    <%   @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.nit %></td>
        <td><%= cliente.direccion %></td>
        <td><%= cliente.telefono %></td>
        <td><%= best_in_place cliente, :user_id,  :as => :select,
        :collection => @comerciales.map{|i| [i.id, i.nombre]}%></td>
        <td><%= link_to '<button class="btn btn-outline-primary"><span><i class="ion-person-stalker"></i></i></span></button>'.html_safe, cliente %></td>
        <td><%= link_to '<button class="btn btn-outline-warning"><span><i class="ion-paintbrush"></i></i></span></button>'.html_safe, edit_cliente_path(cliente) %></td>
        <td><%= link_to '<button class="btn btn-outline-danger"><span><i class="ion-trash-a"></i></i></span></button>'.html_safe, cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="pull-right cont_oc">
  <%= will_paginate @clientes, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>



<%if current_user.rol.cargo=="Gerente Comercial"%>
  <button class="btn btn-success" data-toggle="modal" data-target="#modalExcel">Importar Clientes Desde Excel</button>
  <br>
  <br>
  <%= link_to '<button type="button" class="btn btn-dark"><i class="ion-clipboard"></i>Registrar Cliente nuevo</button>'.html_safe, new_cliente_path %>


  <!-- Modal Excel -->

  <div class="modal fade fullscreen-modal " id="modalExcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content col-12">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Importar Clientes Desde Excel</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="container">
            <h1>Instrucciones:</h1>
            <h6> <strong>-</strong> Para importar Clientes asegurese de que el orden las las columnas sean los siguientes: <br> &nbsp; <strong> Nombre del Cliente, Nit, Dirección, Telefono.</strong>  </h6>
            <h6><strong>-</strong> Además El archivo tendrá que pertenecer a alguna de estas extenciones:<br> &nbsp; <strong>".xls", ".xlsx", ".csv". </strong></h6>
              <%= form_tag import_from_excel_path, multipart: true do %> <br>
              <%= file_field_tag :file %> <br> <br>
              <%= submit_tag "Importar", :class=> "btn btn-primary"%>
            <% end %>
            <h1><%=@user_id%></h1>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

        </div>

      </div>
    </div>
  <%elsif current_user.rol.cargo=="Administrador"%>
    <button class="btn btn-success" data-toggle="modal" data-target="#modalExcel">Importar Clientes Desde Excel</button>
    <br>
    <br>
    <%= link_to '<button type="button" class="btn btn-dark"><i class="ion-clipboard"></i>Registrar Cliente nuevo</button>'.html_safe, new_cliente_path %>


    <!-- Modal Excel -->

    <div class="modal fade fullscreen-modal " id="modalExcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content col-12">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Importar Clientes Desde Excel</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="container">
              <h1>Instrucciones:</h1>
              <h6> <strong>-</strong> Para importar Clientes asegurese de que el orden las las columnas sean los siguientes: <br> &nbsp; <strong> Nombre del Cliente, Nit, Dirección, Telefono.</strong>  </h6>
              <h6><strong>-</strong> Además El archivo tendrá que pertenecer a alguna de estas extenciones:<br> &nbsp; <strong>".xls", ".xlsx", ".csv". </strong></h6>
                <%= form_tag import_from_excel_path, multipart: true do %> <br>
                <%= file_field_tag :file %> <br> <br>
                <%= submit_tag "Importar", :class=> "btn btn-primary"%>
              <% end %>
              <h1><%=@user_id%></h1>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

          </div>

        </div>
      </div>
    </div>


    <%elsif current_user.rol.cargo=="Producción"%>









      <!-- Modal Excel -->

      <div class="modal fade fullscreen-modal " id="modalExcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content col-12">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Importar Clientes Desde Excel</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="container">
                <h1>Instrucciones:</h1>
                <h6> <strong>-</strong> Para importar Clientes asegurese de que el orden las las columnas sean los siguientes: <br> &nbsp; <strong> Nombre del Cliente, Nit, Dirección, Telefono.</strong>  </h6>
                <h6><strong>-</strong> Además El archivo tendrá que pertenecer a alguna de estas extenciones:<br> &nbsp; <strong>".xls", ".xlsx", ".csv". </strong></h6>
                  <%= form_tag import_from_excel_path, multipart: true do %> <br>
                  <%= file_field_tag :file %> <br> <br>
                  <%= submit_tag "Importar", :class=> "btn btn-primary"%>
                <% end %>
                <h1><%=@user_id%></h1>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

            </div>

          </div>
        </div>
      </div>


    <%end%>

app/views/clientes/vista_subir_excel.html.erb
<p id="notice"><%= notice %></p>

<% if @errores %>
  <% @errores.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<h1>Importar Clientes de Excel</h1>
 <%= form_tag import_from_excel_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import", :class=> "btn"%>
<% end %>
<h1><%=@user_id%></h1>