config/routes.rb
Rails.application.routes.draw do
  resources :procesos_maquinas
  resources :habilitar_rol_maquinas
  resources :programaciones_op_maquinas
  resources :variables_estandar
  resources :contenedores_de_acabados
  resources :acabados
  resources :lugares_despachos
  resources :nombres_facturaciones
  resources :contenedores_de_maquinas
  resources :linea_de_colores
  resources :materiales
  resources :contenedores_de_ordenes
  resources :contenedor_de_remisiones
  resources :facturas
  resources :transiciones
  resources :desarrollos_de_tintas
  resources :ordenes_produccion
  resources :compromisos_de_entrega
  resources :tintas_fop_retiro
  resources :tintas_fop_tiro
  resources :formulas_tinta
  resources :tintas_formuladas
  resources :tintas
  resources :mallas
  resources :formatos_op
  resources :formato_ops
  resources :meses
  resources :remisiones
  resources :facturas_despacho
  resources :tiempos_de_entregas
  resources :ordenes_de_produccion
  resources :despachos
  resources :pedidos
  resources :lineas_de_impresiones
  resources :contactos
  resources :clientes
  devise_for :users
  resources :users
  resources :roles
  resources :montajes
  resources :piezas
  resources :maquinas
  resources :lineas_productos
  resources :lineas_de_colores
  resources :piezas_a_decorar


  get 'produccion', to: 'pedidos#produccion', as: :produccion

  get 'entregas', to: 'pedidos#entregas', as: :entregas

  root :to => 'static_pages#home'

  get 'info_produccion', to: 'ordenes_de_produccion#info_produccion', as: :info_produccion

  post 'crearNuevaOrden', to: 'ordenes_de_produccion#crearNuevaOrden', as: :crearNuevaOrden

  get 'consultar_despacho/:id', to: 'pedidos#consultar_despacho', as: :consultar_despacho

  get 'info_despacho/:id', to: 'tiempos_de_entregas#info_despacho', as: :info_despacho

  get 'cambiar_estado/:id', to: 'pedidos#cambiar_estado', as: :cambiar_estado

  get 'cambiar_estado_a_Pedido/:id', to: 'pedidos#cambiar_estado_a_Pedido', as: :cambiar_estado_a_Pedido

  get 'genera_reporte_pedido', to: 'pedidos#genera_reporte_pedido', as: :genera_reporte_pedido


# resources :ordenes_de_produccion, :only => :none do
#      get :info_produccion
#  end


  resources :contactos, :only => :none do
      get :vista
  end

  post 'import_from_excel' => "clientes#import_from_excel"
  get 'vista_subir_excel', to: 'clientes#vista_subir_excel'
  post 'import_contactos_from_excel/:id' => "clientes#import_contactos_from_excel", as: :import_contactos_from_excel
  get 'contactos_subir_excel', to: 'clientes#contactos_subir_excel'

  get 'cambiar_proceso/:id', to: 'ordenes_produccion#cambiar_proceso', as: :cambiar_proceso
  get 'cambiar_estado_pantalla/:id', to: 'ordenes_produccion#cambiar_estado_pantalla', as: :cambiar_estado_pantalla
  get 'cambiar_estado_color/:id', to: 'ordenes_produccion#cambiar_estado_color', as: :cambiar_estado_color
  get 'cambiar_estado_corte_material/:id', to: 'ordenes_produccion#cambiar_estado_corte_material', as: :cambiar_estado_corte_material
  get 'cambiar_estado_impresion/:id', to: 'ordenes_produccion#cambiar_estado_impresion', as: :cambiar_estado_impresion
  get 'cambiar_estado_troquel/:id', to: 'ordenes_produccion#cambiar_estado_troquel', as: :cambiar_estado_troquel
  get 'cambiar_estado_acabados/:id', to: 'ordenes_produccion#cambiar_estado_acabados', as: :cambiar_estado_acabados
  get 'cambiar_habilitar_impresion/:id', to: 'ordenes_produccion#cambiar_habilitar_impresion', as: :cambiar_habilitar_impresion
  get 'cambiar_habilitar_acabado/:id', to: 'ordenes_produccion#cambiar_habilitar_acabado', as: :cambiar_habilitar_acabado

  get 'despacho_facturas', to: 'tiempos_de_entregas#despacho_facturas', as: :despacho_facturas
  get 'info_despacho_facturas/:id', to: 'tiempos_de_entregas#info_despacho_facturas', as: :info_despacho_facturas
  get 'anexar_num_factura/:id', to: 'tiempos_de_entregas#anexar_num_factura', as: :anexar_num_factura
  get 'consultar_factura', to: 'tiempos_de_entregas#consultar_factura', as: :consultar_factura
  get 'anexar_tiempo_de_entrega', to: 'tiempos_de_entregas#anexar_tiempo_de_entrega', as: :anexar_tiempo_de_entrega
  get 'ver_factura/:id', to: 'tiempos_de_entregas#ver_factura', as: :ver_factura
  get 'cerrar_pedido/:id', to: 'tiempos_de_entregas#cerrar_pedido', as: :cerrar_pedido
  get 'ordenes', to: 'pedidos#ordenes', as: :ordenes

  get 'buscar_fop/:id', to: 'montajes#buscar_fop', as: :buscar_fop

  get 'cargar_form_formato', to: 'ordenes_produccion#cargar_form_formato', as: :cargar_form_formato

  get 'cargar_form', to: 'ordenes_produccion#cargar_form', as: :cargar_form

  post 'import_fop_from_excel' => "formatos_op#import_fop_from_excel", as: :import_fop_from_excel

  post 'import_montaje_from_excel' => "montajes#import_montaje_from_excel", as: :import_montaje_from_excel


  post 'import__MP_from_excel' => "montajes#import__MP_from_excel", as: :import__MP_from_excel

  post 'import_tintas_from_excel' => "tintas#import_tintas_from_excel", as: :import_tintas_from_excel

  post 'import_tintas_formuladas_from_excel' => "tintas_formuladas#import_tintas_formuladas_from_excel", as: :import_tintas_formuladas_from_excel

  post 'import_formulaTintas_from_excel' => "formulas_tinta#import_formulaTintas_from_excel", as: :import_formulaTintas_from_excel

  post 'import_ordenes_produccion_from_excel' => "ordenes_produccion#import_ordenes_produccion_from_excel", as: :import_ordenes_produccion_from_excel

  get 'busquedaTintas', to: 'formulas_tinta#busquedaTintas', as: :busquedaTintas

  get 'busquedaTintasMontaje/:id', to: 'montajes#busquedaTintasMontaje', as: :busquedaTintasMontaje

  get 'select_buscar_montaje/:id', to: 'ordenes_produccion#select_buscar_montaje', as: :select_buscar_montaje

  get 'deshacer_envio/:id', to: 'compromisos_de_entrega#deshacer_envio', as: :deshacer_envio

  get 'produccion_pantallas', to: 'ordenes_produccion#produccion_pantallas', as: :produccion_pantallas
  get 'info_pantallas/:id', to: 'ordenes_produccion#info_pantallas', as: :info_pantallas
  get 'cerrar_pantalla/:id', to: 'ordenes_produccion#cerrar_pantalla', as: :cerrar_pantalla


  get 'produccion_coordinador', to: 'ordenes_produccion#produccion_coordinador', as: :produccion_coordinador
  get 'info_coordinador/:id', to: 'ordenes_produccion#info_coordinador', as: :info_coordinador
  get 'cerrar_materiales/:id', to: 'ordenes_produccion#cerrar_materiales', as: :cerrar_materiales

  get 'produccion_comercial', to: 'ordenes_produccion#produccion_comercial', as: :produccion_comercial

  get 'produccion_color', to: 'ordenes_produccion#produccion_color', as: :produccion_color
  get 'info_color/:id', to: 'ordenes_produccion#info_color', as: :info_color
  get 'cerrar_color/:id', to: 'ordenes_produccion#cerrar_color', as: :cerrar_color
  get 'info_factura/:id', to: 'facturas#info_factura', as: :info_factura

  get 'tintas_select/:id', to: 'montajes#tintas_select', as: :tintas_select


  get 'desarrollar_color/:id', to: 'ordenes_produccion#desarrollar_color', as: :desarrollar_color

  get 'crear_color/:id', to: 'tintas_formuladas#crear_color', as: :crear_color

  get 'desarrollar_tintas_tiro/:id', to: 'ordenes_produccion#desarrollar_tintas_tiro', as: :desarrollar_tintas_tiro

  get 'desarrollar_tintas_retiro/:id', to: 'ordenes_produccion#desarrollar_tintas_retiro', as: :desarrollar_tintas_retiro
  get 'desarrollar_factura/:id', to: 'facturas#desarrollar_factura', as: :desarrollar_factura

  get 'form_ordenes', to: 'montajes#form_ordenes', as: :form_ordenes


  get 'buscador_de_ordenes', to: 'ordenes_produccion#buscador_de_ordenes', as: :buscador_de_ordenes

  post 'buscador_de_ordenes_por_mes', to: 'ordenes_produccion#buscador_de_ordenes_por_mes', as: :buscador_de_ordenes_por_mes
  post 'buscador_de_ordenes_por_fecha', to: 'ordenes_produccion#buscador_de_ordenes_por_fecha', as: :buscador_de_ordenes_por_fecha

  post 'busquda_avanzada_produccion', to: 'ordenes_produccion#busquda_avanzada_produccion', as: :busquda_avanzada_produccion
  get 'cargar_select_advance_search', to: 'ordenes_produccion#cargar_select_advance_search', as: :cargar_select_advance_search

  get 'buscador_de_ordenes_despachos', to: 'compromisos_de_entrega#buscador_de_ordenes_despachos', as: :buscador_de_ordenes_despachos

  get 'buscador_de_fichas', to: 'montajes#buscador_de_fichas', as: :buscador_de_fichas

  get 'buscador_de_tintas', to: 'tintas#buscador_de_tintas', as: :buscador_de_tintas

  get 'buscador_de_tintas_formuladas', to: 'tintas_formuladas#buscador_de_tintas_formuladas', as: :buscador_de_tintas_formuladas

  post 'import_materiales_excel' => "materiales#import_materiales_excel", as: :import_materiales_excel

  get 'contactos_for_select/:id', to: 'montajes#contactos_for_select', as: :contactos_for_select

  get 'reporte_tinta/:id', to: 'ordenes_produccion#reporte_tinta', as: :reporte_tinta
  get 'open_modal_import', to: 'ordenes_produccion#open_modal_import', as: :open_modal_import

  get 'produccion_por_maquinas', to: 'maquinas#produccion_por_maquinas', as: :produccion_por_maquinas
  get 'consulta_por_maquinas/:id', to: 'maquinas#consulta_por_maquinas', as: :consulta_por_maquinas

  get 'detalles_produccion_maquina/:id', to: 'maquinas#detalles_produccion_maquina', as: :detalles_produccion_maquina

  get 'deshacer_programa_maquina/:id', to: 'programaciones_op_maquinas#deshacer_programa_maquina', as: :deshacer_programa_maquina
  get 'confirmar_impresion/:id', to: 'maquinas#confirmar_impresion', as: :confirmar_impresion


  get 'buscar_orden_maquina', to: 'maquinas#buscar_orden_maquina', as: :buscar_orden_maquina

  get 'programacion_maquinas_excel/:id', to: 'maquinas#programacion_maquinas_excel', as: :programacion_maquinas_excel

  get 'select_onchange_search', to: 'contactos#select_onchange_search', as: :select_onchange_search

  post 'blur_edit_machine', to: 'maquinas#blur_edit_machine', as: :blur_edit_machine

app/controllers/programaciones_op_maquinas_controller.rb
class ProgramacionesOpMaquinasController < ApplicationController
  before_action :set_programacion_op_maquina, only: [:show, :edit, :update, :destroy]

  # GET /programaciones_op_maquinas
  # GET /programaciones_op_maquinas.json
  def index
    @programaciones_op_maquinas = ProgramacionOpMaquina.all
  end

  def deshacer_programa_maquina
    #code
    @programacion_op_maquina = ProgramacionOpMaquina.find(params[:id])
    

    respond_to do |format|
      format.js
    end
  end

  # GET /programaciones_op_maquinas/1
  # GET /programaciones_op_maquinas/1.json
  def show
  end

  # GET /programaciones_op_maquinas/new
  def new
    @programacion_op_maquina = ProgramacionOpMaquina.new
  end

  # GET /programaciones_op_maquinas/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /programaciones_op_maquinas
  # POST /programaciones_op_maquinas.json
  def create
    @programacion_op_maquina = ProgramacionOpMaquina.new(programacion_op_maquina_params)

    respond_to do |format|
      if @programacion_op_maquina.save
        format.html { redirect_to @programacion_op_maquina, notice: 'Programacion op maquina was successfully created.' }
        format.json { render :show, status: :created, location: @programacion_op_maquina }
        format.js
      else
        format.html { render :new }
        format.json { render json: @programacion_op_maquina.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /programaciones_op_maquinas/1
  # PATCH/PUT /programaciones_op_maquinas/1.json
  def update
    respond_to do |format|
      if @programacion_op_maquina.update(programacion_op_maquina_params)
        format.html { redirect_to @programacion_op_maquina, notice: 'Programacion op maquina was successfully updated.' }
        format.json { render :show, status: :ok, location: @programacion_op_maquina }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @programacion_op_maquina.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /programaciones_op_maquinas/1
  # DELETE /programaciones_op_maquinas/1.json
  def destroy
    @programacion_op_maquina.destroy
    respond_to do |format|
      format.html { redirect_to programaciones_op_maquinas_url, notice: 'Programacion op maquina was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programacion_op_maquina
      @programacion_op_maquina = ProgramacionOpMaquina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def programacion_op_maquina_params
      params.require(:programacion_op_maquina).permit(:orden_produccion_id,
        :maquina_id, :total_hora, :hora_inicio, :hora_final, :cantidad_maquinas,
        :tiempo_por_maquina, :tiempo_de_montaje, :tiempo_de_desmontaje, :habilitado,
        :complemento,:tirajes_por_hora,:fecha_de_impresion, :fecha_de_impresion_final)
    end
end

app/helpers/programaciones_op_maquinas_helper.rb
module ProgramacionesOpMaquinasHelper
end

app/views/programaciones_op_maquinas/_fila_de_programacion.html.erb
 <%=@programacion_op_maquina.fecha_de_impresion%>





 <td><%=@programacion_op_maquina.orden_produccion.numero_de_orden%></td>
 <td><%=@programacion_op_maquina.orden_produccion.montaje.cliente.nombre%></td>
 <td><%=@programacion_op_maquina.orden_produccion.montaje.nombre%></td>



 <% if @programacion_op_maquina.orden_produccion.compromisos_de_entrega.any? %>
               <!-- true -->



             <%



             %>
             <%cont=0%>
             <%@comparador_fecha = ""%>
             <%contador_enviados = 0%>



             <%@hallado = false%>
             <%@estado_data= false%>
             <% @programacion_op_maquina.orden_produccion.compromisos_de_entrega.each do  |fecha| %>

                     <% if fecha.fecha_de_compromiso != nil  %>
                                 <!-- true -->


                                     <%
                                       fech = fecha.fecha_de_compromiso
                                       fech.strftime("%Y/%m/%d")
                                     %>

                                     <% if fecha.enviado == true %>
                                         <%@estado_data = true%>
                                         <%contador_enviados = contador_enviados + 1%>
                                         <%@cantidades = contador_enviados%>
                                     <% end %>



                             <%if fecha.fecha_de_compromiso < Date.today

                                   puts "******************Dia menor #{@dates}**********************"

                                   @dates= fecha.fecha_de_compromiso
                                   %>

                             <% elsif fecha.fecha_de_compromiso >= Date.today %>

                                     <%
                                       dias = (fecha.fecha_de_compromiso - Date.today).to_i


                                       if dias == 0
                                         @dates= fecha.fecha_de_compromiso
                                         @hallado = true
                                         puts "******************Dia igual #{@dates}**********************"
                                       else
                                         if @hallado == false
                                           @dates= fecha.fecha_de_compromiso
                                           puts "******************Dia mayor #{@dates}**********************"
                                         end
                                       end

                                       %>


                             <% end %>


                             <% end %>

                   <% end %>




                             <td ><%=@dates%> </td>

                 <% else %>

                 <td ><p>Pendiente Por Definir Fecha</p> </td>
                 <% end %>


                 <% if @programacion_op_maquina.orden_produccion.programaciones_op_maquinas.first == nil %>
                   <!-- true -->
                   <td  id=<%="fecha_impresion#{@programacion_op_maquina.orden_produccion.id}"%>> <p>Sin definir</p> </td>
                 <% else %>
                 <td  id=<%="fecha_impresion#{@programacion_op_maquina.orden_produccion.id}"%>> <%=@programacion_op_maquina.orden_produccion.programaciones_op_maquinas.first.fecha_de_impresion%> </td>
                 <% end %>





 <td><%= numero_beuty(@programacion_op_maquina.orden_produccion.cantidad_solicitada.to_i) %></td>

 <!--CANTIDA SOLICITADA-->
 <% if @programacion_op_maquina.orden_produccion.programaciones_op_maquinas.first == nil %>
   <td  > <p>Sin definir</p> </td>
 <% else %>
   <td class="inputSwitch" >
     <span align="left">
       <%=@programacion_op_maquina.orden_produccion.programaciones_op_maquinas.first.cantidad_maquinas %>
     </span>
     <input type="number" style="text-align:left;"/>
   </td>
 <% end %>

 <!--ID PROGRAMACION_OP_MAQUINAS-->
 <% if @programacion_op_maquina.orden_produccion.programaciones_op_maquinas.first == nil %>
   <td class="ocultar" > </td>
 <% else %>
   <td class="ocultar" >
     <span align="left" class="tomar_span_id">
       <%=@programacion_op_maquina.orden_produccion.programaciones_op_maquinas.first.id %>
     </span>

   </td>
 <% end %>

 <!--TIEMPO TOTAL-->
 <% if @programacion_op_maquina.orden_produccion.programaciones_op_maquinas.first == nil %>
   <td  > <p>Sin definir</p> </td>
 <% else %>
   <td  > <%=@programacion_op_maquina.orden_produccion.programaciones_op_maquinas.first.total_hora%> </td>
 <% end %>

 <!--ORDENES DE IMPRESION-->
 <% if @programacion_op_maquina.orden_produccion.impresion == true %>
   <!-- true -->
   <td><%= link_to '<button class="btn btn-outline-success"><span><i class="ion-checkmark-round"></i></span></button>'.html_safe, confirmar_impresion_path(@programacion_op_maquina.orden_produccion), remote: true %></td>
 <% else %>
   <td><%= link_to '<button class="btn btn-outline-warning"><span><i class="ion-qr-scanner"></i></span></button>'.html_safe, confirmar_impresion_path(@programacion_op_maquina.orden_produccion), remote: true %></td>
 <% end %>


 <td><%= link_to '<button class="btn btn-outline-info"><span><i class="ion-stats-bars"></i></span></button>'.html_safe, detalles_produccion_maquina_path(@programacion_op_maquina.orden_produccion), remote: true %></td>



<script type="text/javascript">

//actualizar los datos para ser ordenados ccon el tablesorter
var resort = true;
$('.my-tabla').trigger('updateAll', [resort]);


</script>

app/views/programaciones_op_maquinas/_form.html.erb
<%= simple_form_for(@programacion_op_maquina) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :orden_produccion %>
    <%= f.association :maquina %>
    <%= f.input :total_hora %>
    <%= f.input :hora_inicio %>
    <%= f.input :hora_final %>
    <%= f.input :cantidad_maquinas %>
    <%= f.input :tiempo_por_maquina %>
    <%= f.input :tiempo_de_montaje %>
    <%= f.input :tiempo_de_desmontaje %>
    <%= f.input :habilitado %>
    <%= f.input :complemento %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/programaciones_op_maquinas/_respuesta_programacion.html.erb
<div class="">

  <div class="my_card_pedidos_form my_orden_pedidos">

    <div class="col-6">
      <%= link_to '<button class="btn btn-outline-warning"><span>Editar <i class="ion-paintbrush"></i></span></button>'.html_safe, edit_programacion_op_maquina_path( @programacion_op_maquina), remote: true %>
    </div>

    

  </div>



    <div class="col-12">
      <br>
    </div>


  <table class="table table-responsive">
    <thead>

      <th>FECHA DE IMPRESION</th>
      <th>CANTIDAD TOTAL</th>
      <th>TAMAÑOS TOTALES</th>
      <th>CANTIDAD DE MAQUINAS</th>
      <th>TOTAL EN HORAS</th>
      <th>TIEMPO POR MAQUINAS</th>
      <th>HORA DE INICIO</th>
      <th>TERMINA DE IMPRIMIR</th>
      <th>HORA FINAL</th>

    </thead>
      <tbody>

        <tr>

          <td> <h6> <%=@programacion_op_maquina.fecha_de_impresion%> <span> <i class="ion-calendar"></i> </span> </h6> </td>
          <td> <h6> <%=numero_beuty(@programacion_op_maquina.orden_produccion.cantidad_solicitada.to_i)%> </h6> </td>
          <td> <h6> <%=numero_beuty(@programacion_op_maquina.orden_produccion.tamanos_total.to_i)%> <span> UND</span> </h6 </h6> </td>
          <td> <h6> <%=@programacion_op_maquina.cantidad_maquinas%>  </h6> </td>
          <td> <h6> <%=@programacion_op_maquina.total_hora%> <span> <i class="ion-clock"></i> </span> </h6>  </td>
          <td> <h6> <%=@programacion_op_maquina.tiempo_por_maquina%> <span> <i class="ion-clock"></i> </span></h6>  </td>
          <td> <h6> <%=@programacion_op_maquina.hora_inicio.strftime("%H:%M ")%> <span> <i class="ion-clock"></i> </span> </h6>  </td>
          <td> <h6> <%=@programacion_op_maquina.fecha_de_impresion_final%> <span> <i class="ion-calendar"></i> </span> </h6> </td>
          <td> <h6> <%=@programacion_op_maquina.hora_final.strftime("%H:%M ")%> <span> <i class="ion-clock"></i> </span> </h6> </td>


        </tr>
      </tbody>

  </table>







</div>

app/views/programaciones_op_maquinas/deshacer_programa_maquina.js.erb
$('#formulario_programaciones_op').html("<%= j render 'respuesta_programacion'%>")

app/views/programaciones_op_maquinas/destroy.js.erb
toastr.success("El registro a sido eliminado")

app/views/programaciones_op_maquinas/edit.html.erb
<h1>Editing Programacion Op Maquina</h1>

<%= render 'form', programacion_op_maquina: @programacion_op_maquina %>

<%= link_to 'Show', @programacion_op_maquina %> |
<%= link_to 'Back', programaciones_op_maquinas_path %>

app/views/programaciones_op_maquinas/edit.js.erb
$('#formulario_programaciones_op').html("<%= j render 'fragmentos_edicion_programacion'%>")

app/views/programaciones_op_maquinas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Programaciones Op Maquinas</h1>

<table>
  <thead>
    <tr>
      <th>Orden produccion</th>
      <th>Maquina</th>
      <th>Total hora</th>
      <th>Hora inicio</th>
      <th>Hora final</th>
      <th>Cantidad maquinas</th>
      <th>Tiempo por maquina</th>
      <th>Tiempo de montaje</th>
      <th>Tiempo de desmontaje</th>
      <th>Habilitado</th>
      <th>Complemento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programaciones_op_maquinas.each do |programacion_op_maquina| %>
      <tr>
        <td><%= programacion_op_maquina.orden_produccion %></td>
        <td><%= programacion_op_maquina.maquina %></td>
        <td><%= programacion_op_maquina.total_hora %></td>
        <td><%= programacion_op_maquina.hora_inicio %></td>
        <td><%= programacion_op_maquina.hora_final %></td>
        <td><%= programacion_op_maquina.cantidad_maquinas %></td>
        <td><%= programacion_op_maquina.tiempo_por_maquina %></td>
        <td><%= programacion_op_maquina.tiempo_de_montaje %></td>
        <td><%= programacion_op_maquina.tiempo_de_desmontaje %></td>
        <td><%= programacion_op_maquina.habilitado %></td>
        <td><%= programacion_op_maquina.complemento %></td>
        <td><%= link_to 'Show', programacion_op_maquina %></td>
        <td><%= link_to 'Edit', edit_programacion_op_maquina_path(programacion_op_maquina) %></td>
        <td><%= link_to 'Destroy', programacion_op_maquina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Programacion Op Maquina', new_programacion_op_maquina_path %>

app/views/programaciones_op_maquinas/new.html.erb
<h1>New Programacion Op Maquina</h1>

<%= render 'form', programacion_op_maquina: @programacion_op_maquina %>

<%= link_to 'Back', programaciones_op_maquinas_path %>

app/views/programaciones_op_maquinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Orden produccion:</strong>
  <%= @programacion_op_maquina.orden_produccion %>
</p>

<p>
  <strong>Maquina:</strong>
  <%= @programacion_op_maquina.maquina %>
</p>

<p>
  <strong>Total hora:</strong>
  <%= @programacion_op_maquina.total_hora %>
</p>

<p>
  <strong>Hora inicio:</strong>
  <%= @programacion_op_maquina.hora_inicio %>
</p>

<p>
  <strong>Hora final:</strong>
  <%= @programacion_op_maquina.hora_final %>
</p>

<p>
  <strong>Cantidad maquinas:</strong>
  <%= @programacion_op_maquina.cantidad_maquinas %>
</p>

<p>
  <strong>Tiempo por maquina:</strong>
  <%= @programacion_op_maquina.tiempo_por_maquina %>
</p>

<p>
  <strong>Tiempo de montaje:</strong>
  <%= @programacion_op_maquina.tiempo_de_montaje %>
</p>

<p>
  <strong>Tiempo de desmontaje:</strong>
  <%= @programacion_op_maquina.tiempo_de_desmontaje %>
</p>

<p>
  <strong>Habilitado:</strong>
  <%= @programacion_op_maquina.habilitado %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @programacion_op_maquina.complemento %>
</p>

<%= link_to 'Edit', edit_programacion_op_maquina_path(@programacion_op_maquina) %> |
<%= link_to 'Back', programaciones_op_maquinas_path %>