config/routes.rb
Rails.application.routes.draw do
  resources :procesos_maquinas
  resources :habilitar_rol_maquinas
  resources :programaciones_op_maquinas
  resources :variables_estandar
  resources :contenedores_de_acabados
  resources :acabados
  resources :lugares_despachos
  resources :nombres_facturaciones
  resources :contenedores_de_maquinas
  resources :linea_de_colores
  resources :materiales
  resources :contenedores_de_ordenes
  resources :contenedor_de_remisiones
  resources :facturas
  resources :transiciones
  resources :desarrollos_de_tintas
  resources :ordenes_produccion
  resources :compromisos_de_entrega
  resources :tintas_fop_retiro
  resources :tintas_fop_tiro
  resources :formulas_tinta
  resources :tintas_formuladas
  resources :tintas
  resources :mallas
  resources :formatos_op
  resources :formato_ops
  resources :meses
  resources :remisiones
  resources :facturas_despacho
  resources :tiempos_de_entregas
  resources :ordenes_de_produccion
  resources :despachos
  resources :pedidos
  resources :lineas_de_impresiones
  resources :contactos
  resources :clientes
  devise_for :users
  resources :users
  resources :roles
  resources :montajes
  resources :piezas
  resources :maquinas
  resources :lineas_productos
  resources :lineas_de_colores
  resources :piezas_a_decorar


  get 'produccion', to: 'pedidos#produccion', as: :produccion

  get 'entregas', to: 'pedidos#entregas', as: :entregas

  root :to => 'static_pages#home'

  get 'info_produccion', to: 'ordenes_de_produccion#info_produccion', as: :info_produccion

  post 'crearNuevaOrden', to: 'ordenes_de_produccion#crearNuevaOrden', as: :crearNuevaOrden

  get 'consultar_despacho/:id', to: 'pedidos#consultar_despacho', as: :consultar_despacho

  get 'info_despacho/:id', to: 'tiempos_de_entregas#info_despacho', as: :info_despacho

  get 'cambiar_estado/:id', to: 'pedidos#cambiar_estado', as: :cambiar_estado

  get 'cambiar_estado_a_Pedido/:id', to: 'pedidos#cambiar_estado_a_Pedido', as: :cambiar_estado_a_Pedido

  get 'genera_reporte_pedido', to: 'pedidos#genera_reporte_pedido', as: :genera_reporte_pedido


# resources :ordenes_de_produccion, :only => :none do
#      get :info_produccion
#  end


  resources :contactos, :only => :none do
      get :vista
  end

  post 'import_from_excel' => "clientes#import_from_excel"
  get 'vista_subir_excel', to: 'clientes#vista_subir_excel'
  post 'import_contactos_from_excel/:id' => "clientes#import_contactos_from_excel", as: :import_contactos_from_excel
  get 'contactos_subir_excel', to: 'clientes#contactos_subir_excel'

  get 'cambiar_proceso/:id', to: 'ordenes_produccion#cambiar_proceso', as: :cambiar_proceso
  get 'cambiar_estado_pantalla/:id', to: 'ordenes_produccion#cambiar_estado_pantalla', as: :cambiar_estado_pantalla
  get 'cambiar_estado_color/:id', to: 'ordenes_produccion#cambiar_estado_color', as: :cambiar_estado_color
  get 'cambiar_estado_corte_material/:id', to: 'ordenes_produccion#cambiar_estado_corte_material', as: :cambiar_estado_corte_material
  get 'cambiar_estado_impresion/:id', to: 'ordenes_produccion#cambiar_estado_impresion', as: :cambiar_estado_impresion
  get 'cambiar_estado_troquel/:id', to: 'ordenes_produccion#cambiar_estado_troquel', as: :cambiar_estado_troquel
  get 'cambiar_estado_acabados/:id', to: 'ordenes_produccion#cambiar_estado_acabados', as: :cambiar_estado_acabados
  get 'cambiar_habilitar_impresion/:id', to: 'ordenes_produccion#cambiar_habilitar_impresion', as: :cambiar_habilitar_impresion
  get 'cambiar_habilitar_acabado/:id', to: 'ordenes_produccion#cambiar_habilitar_acabado', as: :cambiar_habilitar_acabado

  get 'despacho_facturas', to: 'tiempos_de_entregas#despacho_facturas', as: :despacho_facturas
  get 'info_despacho_facturas/:id', to: 'tiempos_de_entregas#info_despacho_facturas', as: :info_despacho_facturas
  get 'anexar_num_factura/:id', to: 'tiempos_de_entregas#anexar_num_factura', as: :anexar_num_factura
  get 'consultar_factura', to: 'tiempos_de_entregas#consultar_factura', as: :consultar_factura
  get 'anexar_tiempo_de_entrega', to: 'tiempos_de_entregas#anexar_tiempo_de_entrega', as: :anexar_tiempo_de_entrega
  get 'ver_factura/:id', to: 'tiempos_de_entregas#ver_factura', as: :ver_factura
  get 'cerrar_pedido/:id', to: 'tiempos_de_entregas#cerrar_pedido', as: :cerrar_pedido
  get 'ordenes', to: 'pedidos#ordenes', as: :ordenes

  get 'buscar_fop/:id', to: 'montajes#buscar_fop', as: :buscar_fop

  get 'cargar_form_formato', to: 'ordenes_produccion#cargar_form_formato', as: :cargar_form_formato

  get 'cargar_form', to: 'ordenes_produccion#cargar_form', as: :cargar_form

  post 'import_fop_from_excel' => "formatos_op#import_fop_from_excel", as: :import_fop_from_excel

  post 'import_montaje_from_excel' => "montajes#import_montaje_from_excel", as: :import_montaje_from_excel


  post 'import__MP_from_excel' => "montajes#import__MP_from_excel", as: :import__MP_from_excel

  post 'import_tintas_from_excel' => "tintas#import_tintas_from_excel", as: :import_tintas_from_excel

  post 'import_tintas_formuladas_from_excel' => "tintas_formuladas#import_tintas_formuladas_from_excel", as: :import_tintas_formuladas_from_excel

  post 'import_formulaTintas_from_excel' => "formulas_tinta#import_formulaTintas_from_excel", as: :import_formulaTintas_from_excel

  post 'import_ordenes_produccion_from_excel' => "ordenes_produccion#import_ordenes_produccion_from_excel", as: :import_ordenes_produccion_from_excel

  get 'busquedaTintas', to: 'formulas_tinta#busquedaTintas', as: :busquedaTintas

  get 'busquedaTintasMontaje/:id', to: 'montajes#busquedaTintasMontaje', as: :busquedaTintasMontaje

  get 'select_buscar_montaje/:id', to: 'ordenes_produccion#select_buscar_montaje', as: :select_buscar_montaje

  get 'deshacer_envio/:id', to: 'compromisos_de_entrega#deshacer_envio', as: :deshacer_envio

  get 'produccion_pantallas', to: 'ordenes_produccion#produccion_pantallas', as: :produccion_pantallas
  get 'info_pantallas/:id', to: 'ordenes_produccion#info_pantallas', as: :info_pantallas
  get 'cerrar_pantalla/:id', to: 'ordenes_produccion#cerrar_pantalla', as: :cerrar_pantalla


  get 'produccion_coordinador', to: 'ordenes_produccion#produccion_coordinador', as: :produccion_coordinador
  get 'info_coordinador/:id', to: 'ordenes_produccion#info_coordinador', as: :info_coordinador
  get 'cerrar_materiales/:id', to: 'ordenes_produccion#cerrar_materiales', as: :cerrar_materiales

  get 'produccion_comercial', to: 'ordenes_produccion#produccion_comercial', as: :produccion_comercial

  get 'produccion_color', to: 'ordenes_produccion#produccion_color', as: :produccion_color
  get 'info_color/:id', to: 'ordenes_produccion#info_color', as: :info_color
  get 'cerrar_color/:id', to: 'ordenes_produccion#cerrar_color', as: :cerrar_color
  get 'info_factura/:id', to: 'facturas#info_factura', as: :info_factura

  get 'tintas_select/:id', to: 'montajes#tintas_select', as: :tintas_select


  get 'desarrollar_color/:id', to: 'ordenes_produccion#desarrollar_color', as: :desarrollar_color

  get 'crear_color/:id', to: 'tintas_formuladas#crear_color', as: :crear_color

  get 'desarrollar_tintas_tiro/:id', to: 'ordenes_produccion#desarrollar_tintas_tiro', as: :desarrollar_tintas_tiro

  get 'desarrollar_tintas_retiro/:id', to: 'ordenes_produccion#desarrollar_tintas_retiro', as: :desarrollar_tintas_retiro
  get 'desarrollar_factura/:id', to: 'facturas#desarrollar_factura', as: :desarrollar_factura

  get 'form_ordenes', to: 'montajes#form_ordenes', as: :form_ordenes


  get 'buscador_de_ordenes', to: 'ordenes_produccion#buscador_de_ordenes', as: :buscador_de_ordenes

  post 'buscador_de_ordenes_por_mes', to: 'ordenes_produccion#buscador_de_ordenes_por_mes', as: :buscador_de_ordenes_por_mes
  post 'buscador_de_ordenes_por_fecha', to: 'ordenes_produccion#buscador_de_ordenes_por_fecha', as: :buscador_de_ordenes_por_fecha

  post 'busquda_avanzada_produccion', to: 'ordenes_produccion#busquda_avanzada_produccion', as: :busquda_avanzada_produccion
  get 'cargar_select_advance_search', to: 'ordenes_produccion#cargar_select_advance_search', as: :cargar_select_advance_search

  get 'buscador_de_ordenes_despachos', to: 'compromisos_de_entrega#buscador_de_ordenes_despachos', as: :buscador_de_ordenes_despachos

  get 'buscador_de_fichas', to: 'montajes#buscador_de_fichas', as: :buscador_de_fichas

  get 'buscador_de_tintas', to: 'tintas#buscador_de_tintas', as: :buscador_de_tintas

  get 'buscador_de_tintas_formuladas', to: 'tintas_formuladas#buscador_de_tintas_formuladas', as: :buscador_de_tintas_formuladas

  post 'import_materiales_excel' => "materiales#import_materiales_excel", as: :import_materiales_excel

  get 'contactos_for_select/:id', to: 'montajes#contactos_for_select', as: :contactos_for_select

  get 'reporte_tinta/:id', to: 'ordenes_produccion#reporte_tinta', as: :reporte_tinta
  get 'open_modal_import', to: 'ordenes_produccion#open_modal_import', as: :open_modal_import

  get 'produccion_por_maquinas', to: 'maquinas#produccion_por_maquinas', as: :produccion_por_maquinas
  get 'consulta_por_maquinas/:id', to: 'maquinas#consulta_por_maquinas', as: :consulta_por_maquinas

  get 'detalles_produccion_maquina/:id', to: 'maquinas#detalles_produccion_maquina', as: :detalles_produccion_maquina

  get 'deshacer_programa_maquina/:id', to: 'programaciones_op_maquinas#deshacer_programa_maquina', as: :deshacer_programa_maquina
  get 'confirmar_impresion/:id', to: 'maquinas#confirmar_impresion', as: :confirmar_impresion


  get 'buscar_orden_maquina', to: 'maquinas#buscar_orden_maquina', as: :buscar_orden_maquina

  get 'programacion_maquinas_excel/:id', to: 'maquinas#programacion_maquinas_excel', as: :programacion_maquinas_excel

  get 'select_onchange_search', to: 'contactos#select_onchange_search', as: :select_onchange_search

  post 'blur_edit_machine', to: 'maquinas#blur_edit_machine', as: :blur_edit_machine

app/controllers/ordenes_de_produccion_controller.rb
class OrdenesDeProduccionController < ApplicationController
  before_action :set_orden_de_produccion, only: [:show, :edit, :update, :destroy]

  # GET /ordenes_de_produccion
  # GET /ordenes_de_produccion.json
  def index
    @ordenes_de_produccion = OrdenDeProduccion.all
  end

  def produccion
    @pedidos = Pedido.joins(:contacto)
    @orden_de_produccion = OrdenDeProduccion.new
  end

  def info_produccion
    @my_produccion = Pedido.joins(:ordenes_de_produccion).find(params[:id])
    render json: @my_produccion.to_json(:include => :ordenes_de_produccion)
  end

  # GET /ordenes_de_produccion/1
  # GET /ordenes_de_produccion/1.json
  def show
  end


  # GET /ordenes_de_produccion/new
  def new
    @orden_de_produccion = OrdenDeProduccion.new
  end

  # GET /ordenes_de_produccion/1/edit
  def edit
  end

  # POST /ordenes_de_produccion
  # POST /ordenes_de_produccion.json
  def create
    @orden_de_produccion = OrdenDeProduccion.new(orden_de_produccion_params)
    if @orden_de_produccion.save
      respond_to do |format|
        format.html {redirect_to ordenes_de_produccion_url}
        format.js{}
      end
    end


    #respond_to do |format|
    #  if @orden_de_produccion.save
    #  format.html { redirect_to produccion_url, notice: 'Orden de produccion was successfully created.' }
    #    format.json
    #
    #  else
    #   format.html { render :new }
    #   format.json { render json: @orden_de_produccion.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PATCH/PUT /ordenes_de_produccion/1
  # PATCH/PUT /ordenes_de_produccion/1.json
  def update
    respond_to do |format|
      if @orden_de_produccion.update(orden_de_produccion_params)
        format.html { redirect_to ordenes_de_produccion_url, notice: 'Orden de produccion was successfully updated.' }
        format.json { render :show, status: :ok, location: @orden_de_produccion }
      else
        format.html { render :edit }
        format.json { render json: @orden_de_produccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordenes_de_produccion/1
  # DELETE /ordenes_de_produccion/1.json
  def destroy
    @orden_de_produccion.destroy
    #@ordenes.destroy
    respond_to do |format|
        format.html {redirect_to ordenes_de_produccion_url}
        format.js{}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orden_de_produccion
      @orden_de_produccion = OrdenDeProduccion.find(params[:id])
     # @ordenes=OrdenDeProduccion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orden_de_produccion_params
      params.require(:orden_de_produccion).permit(:pedido_id, :numero_de_orden,
        :descripcion, :fecha_final, :total, :estado,:pedido_id, :codigo, :total, :cantidad, :fecha,:inventario,:estado)
    end
end

app/helpers/ordenes_de_produccion_helper.rb
module OrdenesDeProduccionHelper
end

app/views/ordenes_de_produccion/_form.html.erb
<%= simple_form_for(@orden_de_produccion) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :pedido %>
    <%= f.input :numero_de_orden %>
    <%= f.input :descripcion %>
    <%= f.input :fecha_final %>
    <%= f.input :total %>
    <%= f.input :codigo %>
    <%= f.input :cantidad %>
    <%= f.input :fecha %>
    <%= f.input :inventario %>
    <%= f.input :estado %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ordenes_de_produccion/_orden_de_produccion.html.erb
<tr id=<%="orden_#{@orden_de_produccion.id}"%>>
    <td><%=best_in_place @orden_de_produccion,:numero_de_orden, :as => :input%></td>
    <td><%=best_in_place @orden_de_produccion,:codigo, as: :input%></td>
    <td><%=best_in_place  @orden_de_produccion,:descripcion, as: :input%></td>
    <td><%=best_in_place @orden_de_produccion,:cantidad, as: :input%></td>
    <td><%=best_in_place @orden_de_produccion,:fecha, as: :input%></td>
    <td><%= link_to '<button class="btn btn-outline-danger borrar"><span><i class="ion-trash-a"></i></i></span></button>'.html_safe, @orden_de_produccion, method: :delete, id:'borrar',remote: true,data: { confirm: 'Are you sure?' } %></td>
</tr> 
<script>
    toastr.error('cargars')
    jQuery(".best_in_place").best_in_place();
</script>

app/views/ordenes_de_produccion/create.js.erb
toastr.error('Entra la Create')

jQuery(".best_in_place").best_in_place();

$('#orden_de_produccion_numero_de_orden').val(' ');
$("#orden_de_produccion_codigo").val("");
$("#orden_de_produccion_descripcion").val("");
$("#orden_de_produccion_cantidad").val("");
$("#fecha").val("");

$("#Agrego").append("<%= j render @orden_de_produccion%>");

app/views/ordenes_de_produccion/destroy.js.erb
toastr.error('Entra al Destroy')
$('#orden_<%=@orden_de_produccion.id%>').remove()
jQuery(".best_in_place").best_in_place();

app/views/ordenes_de_produccion/edit.html.erb
<h1>Editing Orden De Produccion</h1>

<%= render 'form', orden_de_produccion: @orden_de_produccion %>

<%= link_to 'Show', @orden_de_produccion %> |
<%= link_to 'Back', ordenes_de_produccion_path %>

app/views/ordenes_de_produccion/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordenes De Produccion</h1>

<table>
  <thead>
    <tr>
      <th>Pedido</th>
      <th>Numero de orden</th>
      <th>Descripcion</th>
      <th>Fecha final</th>
      <th>Total</th>
      <th>Codigo</th>
      <th>Cantidad</th>
      <th>Fecha</th>
      <th>Inventario</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordenes_de_produccion.each do |orden_de_produccion| %>
      <tr>
        <td><%= orden_de_produccion.pedido %></td>
        <td><%= orden_de_produccion.numero_de_orden %></td>
        <td><%= orden_de_produccion.descripcion %></td>
        <td><%= orden_de_produccion.fecha_final %></td>
        <td><%= orden_de_produccion.total %></td>
        <td><%= orden_de_produccion.codigo %></td>
        <td><%= orden_de_produccion.cantidad %></td>
        <td><%= orden_de_produccion.fecha %></td>
        <td><%= orden_de_produccion.inventario %></td>
        <td><%= orden_de_produccion.estado %></td>
        <td><%= link_to 'Show', orden_de_produccion %></td>
        <td><%= link_to 'Edit', edit_orden_de_produccion_path(orden_de_produccion) %></td>
        <td><%= link_to 'Destroy', orden_de_produccion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orden De Produccion', new_orden_de_produccion_path %>

app/views/ordenes_de_produccion/new.html.erb
<h1>New Orden De Produccion</h1>

<%= render 'form', orden_de_produccion: @orden_de_produccion %>

<%= link_to 'Back', ordenes_de_produccion_path %>

app/views/ordenes_de_produccion/produccion.html.erb
<p id="notice"><%= notice %></p>

<h1>Pedidos Para Producción</h1>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Numero de pedido</th>
      <th>Descripcion Del Producto</th>
      <th>Numero de Cotización</th>
      <th>Fecha de pedido</th>
      <th>Digitado</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td class="cliente"><%= pedido.contacto.cliente.nombre %></td>
        <td ><%=best_in_place pedido, :numero_de_pedido,as: :input %></td>
        <td class="descripcion"><%= pedido.descripcion %></td>
        <td><%= pedido.numero_cotizacion %></td>
        <!--td><!--%= pedido.producto %></td-->
        <td><%= pedido.fecha_de_pedido %></td>
        <td><%= pedido.created_at%></td>



        <td><%= link_to '<button type="button" id="crearProduccion" data-toggle="modal" data-target="" class="btn btn-outline-info"><span><i class="ion-plus-round"></i></span></button>'.html_safe, orden_de_produccion_path(pedido), id:'nuevo_task', remote:true %></td>
        <!--td><!--%= link_to '<button class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModal"><span><i class="ion-clipboard"></i></i></span></button>'.html_safe, pedido %></td-->
      </tr>

    <% end %>
  </tbody>
</table>

<br>







<div class="modal my_modal fade my_modal_orden_pedido " id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog  modal-lg"  role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ordenes de Producción</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="activarmodal"></div>
      <div class="modal-body">
        <form id="activarmodal">

        </form>
      </div>
      <div class="modal-footer">

          <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/ordenes_de_produccion/produccion.js.erb
toastr.error('Entra la show')
console.log(<%=@p%>)
$('#exampleModal').modal('show');

app/views/ordenes_de_produccion/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pedido:</strong>
  <%= @orden_de_produccion.pedido %>
</p>

<p>
  <strong>Numero de orden:</strong>
  <%= @orden_de_produccion.numero_de_orden %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @orden_de_produccion.descripcion %>
</p>

<p>
  <strong>Fecha final:</strong>
  <%= @orden_de_produccion.fecha_final %>
</p>

<p>
  <strong>Total:</strong>
  <%= @orden_de_produccion.total %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @orden_de_produccion.codigo %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @orden_de_produccion.cantidad %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @orden_de_produccion.fecha %>
</p>

<p>
  <strong>Inventario:</strong>
  <%= @orden_de_produccion.inventario %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @orden_de_produccion.estado %>
</p>

<%= link_to 'Edit', edit_orden_de_produccion_path(@orden_de_produccion) %> |
<%= link_to 'Back', ordenes_de_produccion_path %>

app/views/ordenes_de_produccion/show.js.erb
$("#activarmodal").html("<%= j render "form_content"%>");
$('#exampleModal').modal('show');
$('#ocultar_pedido').hide();

jQuery(".best_in_place").best_in_place();
$('.ocultar_fecha').hide();
$('.fecha').focusout(function(){

  var this_fecha = $(this).parents("tr").find(".fecha").val();
  $(this).parents("tr").find(".my_fecha").val(this_fecha);

})

$('form').on('click', '.remove_detalle', function(event) {
  $(this).prev('input[type=hidden]').val('1');
  $(this).closest('tr').remove();
  return event.preventDefault();
});

$('form').on('click', '.add_detalle', function(event) {
  var regexp, time;
  time = new Date().getTime();
  regexp = new RegExp($(this).data('id'), 'g');
  $('.fields_detalle').append($(this).data('fields').replace(regexp, time));
  $('.ocultar_fecha').hide();
  $('.fecha').focusout(function(){

    var this_fecha = $(this).parents("tr").find(".fecha").val();
    $(this).parents("tr").find(".my_fecha").val(this_fecha);

  })

  return event.preventDefault();
});