config/routes.rb
Rails.application.routes.draw do
  resources :procesos_maquinas
  resources :habilitar_rol_maquinas
  resources :programaciones_op_maquinas
  resources :variables_estandar
  resources :contenedores_de_acabados
  resources :acabados
  resources :lugares_despachos
  resources :nombres_facturaciones
  resources :contenedores_de_maquinas
  resources :linea_de_colores
  resources :materiales
  resources :contenedores_de_ordenes
  resources :contenedor_de_remisiones
  resources :facturas
  resources :transiciones
  resources :desarrollos_de_tintas
  resources :ordenes_produccion
  resources :compromisos_de_entrega
  resources :tintas_fop_retiro
  resources :tintas_fop_tiro
  resources :formulas_tinta
  resources :tintas_formuladas
  resources :tintas
  resources :mallas
  resources :formatos_op
  resources :formato_ops
  resources :meses
  resources :remisiones
  resources :facturas_despacho
  resources :tiempos_de_entregas
  resources :ordenes_de_produccion
  resources :despachos
  resources :pedidos
  resources :lineas_de_impresiones
  resources :contactos
  resources :clientes
  devise_for :users
  resources :users
  resources :roles
  resources :montajes
  resources :piezas
  resources :maquinas
  resources :lineas_productos
  resources :lineas_de_colores
  resources :piezas_a_decorar


  get 'produccion', to: 'pedidos#produccion', as: :produccion

  get 'entregas', to: 'pedidos#entregas', as: :entregas

  root :to => 'static_pages#home'

  get 'info_produccion', to: 'ordenes_de_produccion#info_produccion', as: :info_produccion

  post 'crearNuevaOrden', to: 'ordenes_de_produccion#crearNuevaOrden', as: :crearNuevaOrden

  get 'consultar_despacho/:id', to: 'pedidos#consultar_despacho', as: :consultar_despacho

  get 'info_despacho/:id', to: 'tiempos_de_entregas#info_despacho', as: :info_despacho

  get 'cambiar_estado/:id', to: 'pedidos#cambiar_estado', as: :cambiar_estado

  get 'cambiar_estado_a_Pedido/:id', to: 'pedidos#cambiar_estado_a_Pedido', as: :cambiar_estado_a_Pedido

  get 'genera_reporte_pedido', to: 'pedidos#genera_reporte_pedido', as: :genera_reporte_pedido


# resources :ordenes_de_produccion, :only => :none do
#      get :info_produccion
#  end


  resources :contactos, :only => :none do
      get :vista
  end

  post 'import_from_excel' => "clientes#import_from_excel"
  get 'vista_subir_excel', to: 'clientes#vista_subir_excel'
  post 'import_contactos_from_excel/:id' => "clientes#import_contactos_from_excel", as: :import_contactos_from_excel
  get 'contactos_subir_excel', to: 'clientes#contactos_subir_excel'

  get 'cambiar_proceso/:id', to: 'ordenes_produccion#cambiar_proceso', as: :cambiar_proceso
  get 'cambiar_estado_pantalla/:id', to: 'ordenes_produccion#cambiar_estado_pantalla', as: :cambiar_estado_pantalla
  get 'cambiar_estado_color/:id', to: 'ordenes_produccion#cambiar_estado_color', as: :cambiar_estado_color
  get 'cambiar_estado_corte_material/:id', to: 'ordenes_produccion#cambiar_estado_corte_material', as: :cambiar_estado_corte_material
  get 'cambiar_estado_impresion/:id', to: 'ordenes_produccion#cambiar_estado_impresion', as: :cambiar_estado_impresion
  get 'cambiar_estado_troquel/:id', to: 'ordenes_produccion#cambiar_estado_troquel', as: :cambiar_estado_troquel
  get 'cambiar_estado_acabados/:id', to: 'ordenes_produccion#cambiar_estado_acabados', as: :cambiar_estado_acabados
  get 'cambiar_habilitar_impresion/:id', to: 'ordenes_produccion#cambiar_habilitar_impresion', as: :cambiar_habilitar_impresion
  get 'cambiar_habilitar_acabado/:id', to: 'ordenes_produccion#cambiar_habilitar_acabado', as: :cambiar_habilitar_acabado

  get 'despacho_facturas', to: 'tiempos_de_entregas#despacho_facturas', as: :despacho_facturas
  get 'info_despacho_facturas/:id', to: 'tiempos_de_entregas#info_despacho_facturas', as: :info_despacho_facturas
  get 'anexar_num_factura/:id', to: 'tiempos_de_entregas#anexar_num_factura', as: :anexar_num_factura
  get 'consultar_factura', to: 'tiempos_de_entregas#consultar_factura', as: :consultar_factura
  get 'anexar_tiempo_de_entrega', to: 'tiempos_de_entregas#anexar_tiempo_de_entrega', as: :anexar_tiempo_de_entrega
  get 'ver_factura/:id', to: 'tiempos_de_entregas#ver_factura', as: :ver_factura
  get 'cerrar_pedido/:id', to: 'tiempos_de_entregas#cerrar_pedido', as: :cerrar_pedido
  get 'ordenes', to: 'pedidos#ordenes', as: :ordenes

  get 'buscar_fop/:id', to: 'montajes#buscar_fop', as: :buscar_fop

  get 'cargar_form_formato', to: 'ordenes_produccion#cargar_form_formato', as: :cargar_form_formato

  get 'cargar_form', to: 'ordenes_produccion#cargar_form', as: :cargar_form

  post 'import_fop_from_excel' => "formatos_op#import_fop_from_excel", as: :import_fop_from_excel

  post 'import_montaje_from_excel' => "montajes#import_montaje_from_excel", as: :import_montaje_from_excel


  post 'import__MP_from_excel' => "montajes#import__MP_from_excel", as: :import__MP_from_excel

  post 'import_tintas_from_excel' => "tintas#import_tintas_from_excel", as: :import_tintas_from_excel

  post 'import_tintas_formuladas_from_excel' => "tintas_formuladas#import_tintas_formuladas_from_excel", as: :import_tintas_formuladas_from_excel

  post 'import_formulaTintas_from_excel' => "formulas_tinta#import_formulaTintas_from_excel", as: :import_formulaTintas_from_excel

  post 'import_ordenes_produccion_from_excel' => "ordenes_produccion#import_ordenes_produccion_from_excel", as: :import_ordenes_produccion_from_excel

  get 'busquedaTintas', to: 'formulas_tinta#busquedaTintas', as: :busquedaTintas

  get 'busquedaTintasMontaje/:id', to: 'montajes#busquedaTintasMontaje', as: :busquedaTintasMontaje

  get 'select_buscar_montaje/:id', to: 'ordenes_produccion#select_buscar_montaje', as: :select_buscar_montaje

  get 'deshacer_envio/:id', to: 'compromisos_de_entrega#deshacer_envio', as: :deshacer_envio

  get 'produccion_pantallas', to: 'ordenes_produccion#produccion_pantallas', as: :produccion_pantallas
  get 'info_pantallas/:id', to: 'ordenes_produccion#info_pantallas', as: :info_pantallas
  get 'cerrar_pantalla/:id', to: 'ordenes_produccion#cerrar_pantalla', as: :cerrar_pantalla


  get 'produccion_coordinador', to: 'ordenes_produccion#produccion_coordinador', as: :produccion_coordinador
  get 'info_coordinador/:id', to: 'ordenes_produccion#info_coordinador', as: :info_coordinador
  get 'cerrar_materiales/:id', to: 'ordenes_produccion#cerrar_materiales', as: :cerrar_materiales

  get 'produccion_comercial', to: 'ordenes_produccion#produccion_comercial', as: :produccion_comercial

  get 'produccion_color', to: 'ordenes_produccion#produccion_color', as: :produccion_color
  get 'info_color/:id', to: 'ordenes_produccion#info_color', as: :info_color
  get 'cerrar_color/:id', to: 'ordenes_produccion#cerrar_color', as: :cerrar_color
  get 'info_factura/:id', to: 'facturas#info_factura', as: :info_factura

  get 'tintas_select/:id', to: 'montajes#tintas_select', as: :tintas_select


  get 'desarrollar_color/:id', to: 'ordenes_produccion#desarrollar_color', as: :desarrollar_color

  get 'crear_color/:id', to: 'tintas_formuladas#crear_color', as: :crear_color

  get 'desarrollar_tintas_tiro/:id', to: 'ordenes_produccion#desarrollar_tintas_tiro', as: :desarrollar_tintas_tiro

  get 'desarrollar_tintas_retiro/:id', to: 'ordenes_produccion#desarrollar_tintas_retiro', as: :desarrollar_tintas_retiro
  get 'desarrollar_factura/:id', to: 'facturas#desarrollar_factura', as: :desarrollar_factura

  get 'form_ordenes', to: 'montajes#form_ordenes', as: :form_ordenes


  get 'buscador_de_ordenes', to: 'ordenes_produccion#buscador_de_ordenes', as: :buscador_de_ordenes

  post 'buscador_de_ordenes_por_mes', to: 'ordenes_produccion#buscador_de_ordenes_por_mes', as: :buscador_de_ordenes_por_mes
  post 'buscador_de_ordenes_por_fecha', to: 'ordenes_produccion#buscador_de_ordenes_por_fecha', as: :buscador_de_ordenes_por_fecha

  post 'busquda_avanzada_produccion', to: 'ordenes_produccion#busquda_avanzada_produccion', as: :busquda_avanzada_produccion
  get 'cargar_select_advance_search', to: 'ordenes_produccion#cargar_select_advance_search', as: :cargar_select_advance_search

  get 'buscador_de_ordenes_despachos', to: 'compromisos_de_entrega#buscador_de_ordenes_despachos', as: :buscador_de_ordenes_despachos

  get 'buscador_de_fichas', to: 'montajes#buscador_de_fichas', as: :buscador_de_fichas

  get 'buscador_de_tintas', to: 'tintas#buscador_de_tintas', as: :buscador_de_tintas

  get 'buscador_de_tintas_formuladas', to: 'tintas_formuladas#buscador_de_tintas_formuladas', as: :buscador_de_tintas_formuladas

  post 'import_materiales_excel' => "materiales#import_materiales_excel", as: :import_materiales_excel

  get 'contactos_for_select/:id', to: 'montajes#contactos_for_select', as: :contactos_for_select

  get 'reporte_tinta/:id', to: 'ordenes_produccion#reporte_tinta', as: :reporte_tinta
  get 'open_modal_import', to: 'ordenes_produccion#open_modal_import', as: :open_modal_import

  get 'produccion_por_maquinas', to: 'maquinas#produccion_por_maquinas', as: :produccion_por_maquinas
  get 'consulta_por_maquinas/:id', to: 'maquinas#consulta_por_maquinas', as: :consulta_por_maquinas

  get 'detalles_produccion_maquina/:id', to: 'maquinas#detalles_produccion_maquina', as: :detalles_produccion_maquina

  get 'deshacer_programa_maquina/:id', to: 'programaciones_op_maquinas#deshacer_programa_maquina', as: :deshacer_programa_maquina
  get 'confirmar_impresion/:id', to: 'maquinas#confirmar_impresion', as: :confirmar_impresion


  get 'buscar_orden_maquina', to: 'maquinas#buscar_orden_maquina', as: :buscar_orden_maquina

  get 'programacion_maquinas_excel/:id', to: 'maquinas#programacion_maquinas_excel', as: :programacion_maquinas_excel

  get 'select_onchange_search', to: 'contactos#select_onchange_search', as: :select_onchange_search

  post 'blur_edit_machine', to: 'maquinas#blur_edit_machine', as: :blur_edit_machine

app/controllers/facturas_despacho_controller.rb
class FacturasDespachoController < ApplicationController
  before_action :set_factura_despacho, only: [:show, :edit, :update, :destroy]

  # GET /facturas_despacho
  # GET /facturas_despacho.json
  def index
    @facturas_despacho = FacturaDespacho.all
  end

  # GET /facturas_despacho/1
  # GET /facturas_despacho/1.json
  def show
  end

  # GET /facturas_despacho/new
  def new
    @factura_despacho = FacturaDespacho.new
    @factura_despacho.remisiones.build
    @remision=Remision.new
  end

  # GET /facturas_despacho/1/edit
  def edit
  end

  # POST /facturas_despacho
  # POST /facturas_despacho.json
  def create
    @factura_despacho = FacturaDespacho.new(factura_despacho_params)

    respond_to do |format|
      if @factura_despacho.save
        format.html {redirect_to tiempos_de_entrega_url}
        format.js{}
      else
        format.html { render :new }
        format.json { render json: @factura_despacho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facturas_despacho/1
  # PATCH/PUT /facturas_despacho/1.json
  def update
    respond_to do |format|
      if @factura_despacho.update(factura_despacho_params)
        format.html {redirect_to tiempos_de_entrega_url}
        format.js{}
      else
        format.html { render :edit }
        format.json { render json: @factura_despacho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facturas_despacho/1
  # DELETE /facturas_despacho/1.json
  def destroy
    @factura_despacho.destroy
    respond_to do |format|
      format.html {redirect_to tiempos_de_entrega_url}
      format.js{}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factura_despacho
      @factura_despacho = FacturaDespacho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factura_despacho_params
      params.require(:factura_despacho).permit(:tiempos_de_entrega_id, :numero_de_factura, :total_facturado, :iva, :descuento, :cancelada, :cantidad_faltante, :total_enviado, :estado,
      remisiones_attributes:[:factura_despacho_id, :numero_de_remision, :fecha_de_despacho, :cantidad_enviada, :precio_a_facturar, :cantidad_faltante, :entrega_cumplida, :estado])
    end
end

app/helpers/facturas_despacho_helper.rb
module FacturasDespachoHelper
end

app/views/facturas_despacho/_anexar_remision.html.erb
<%= simple_form_for(@factura_despacho) do |f| %>
  <%= f.error_notification %>
  <table class="table" id="factura_<%=factura.id%>">
    <thead class="table-primary">
      <th colspan="4"><h1>Numero de Factura: <%=f.numero_de_factura%></h1></th>
      <th>
           <!--%= link_to_add_remision_extra('<button type="button" id="pruebaSelect" class="btn btn-outline-warning"><span><i class="ion-plus-round"></i></span></button>'.html_safe, f, :remisiones, class: '') %-->
           <%= link_to '<button type="button" id="pruebaSelect" class="btn btn-outline-warning"><span><i class="ion-plus-round"></i></span></button>'.html_safe, edit_factura_despacho_path(factura), remote: true %>
           <!--button type="button" id="pruebaSelect" class="btn btn-outline-warning formularioRemisionesFields"><span><i class="ion-plus-round"></i></span></button-->
      </th>
      <th>
        <%= link_to '<button class="btn btn-outline-danger borrar"><span><i class="ion-trash-a"></i></i></span></button>'.html_safe,
        factura, method: :delete, id:'borrar',remote: true,data: { confirm: 'Are you sure?' } %>
      </th>
    </thead>
    <thead>
      <th>N° De Remisión</th>
      <th>Fecha</th>
      <th>Cantidad Envidad</th>
      <th>Precio Facturado</th>
      <th></th>
    </thead>
    <tbody class='add_remision_extra'>

      <tr>
        <td><%=remisiones.numero_de_remision%></td>
        <td><%=remisiones.fecha_de_despacho%></td>
        <td><%=remisiones.cantidad_enviada%></td>
        <td><%=remisiones.precio_a_facturar%></td>
      </tr>

    </tbody>
  </table>

<% end %>

app/views/facturas_despacho/_factura_despacho.html.erb
<%= simple_form_for(@factura_despacho, remote: true) do |f| %>
  <%= f.error_notification %>
  <table class="table" id=<%="factura_#{@factura_despacho.id}"%>>
    <thead class="">
      <th colspan="4"><h1>Numero de Factura: <%=@factura_despacho.numero_de_factura%></h1>
    </th>
    <th class="">
     <%= link_to_add_remision('<button type="button" id="pruebaSelect" class="btn btn-outline-warning"><span><i class="ion-plus-round"></i></span></button>'.html_safe, f, :remisiones, class: '') %>
  </th>
    <th><%= link_to '<button class="btn btn-outline-danger borrar"><span><i class="ion-trash-a"></i></i></span></button>'.html_safe, @factura_despacho, method: :delete, id:'borrar',remote: true,data: { confirm: 'Are you sure?' } %></th>
    </thead>
    <thead>
      <th>N° De Remisión</th>
      <th>Fecha</th>
      <th>Cantidad Envidad</th>
      <th>Precio Facturado</th>
      <th></th>
      <th></th>

    </thead>
    <tbody id= <%="fields_remisiones_new#{@factura_despacho.id}"%>>
      <%@factura_despacho.remisiones.each do |remisiones|%>
      <tr>
        <td><%=remisiones.numero_de_remision%></td>
        <td><%=remisiones.fecha_de_despacho%></td>
        <td><%=remisiones.cantidad_enviada%></td>
        <td><%=remisiones.precio_a_facturar%></td>
        <td></td>
        <td></td>

      </tr>
      <%end%>



    </tbody>
  </table>
<%end%>

<script>
$('form').on('click', '.remove_remisiones', function(event) {
  $(this).prev('input[type=hidden]').val('1');
  $(this).closest('tr').remove();
  return event.preventDefault();
});

$('form').on('click', '.add_remisiones', function(event) {
  var regexp, time;
  time = new Date().getTime();
  regexp = new RegExp($(this).data('id'), 'g');
  $(<%="fields_remisiones_new#{@factura_despacho.id}"%>).append($(this).data('fields').replace(regexp, time));
  $('.ocultar_fecha').hide();
  $('.fecha').focusout(function(){

    var this_fecha = $(this).parents("tr").find(".fecha").val();
    $(this).parents("tr").find(".my_fecha").val(this_fecha);
    var validar_fecha = $(this).parents("tr").find(".my_fecha").val();
  })
  return event.preventDefault();
});

</script>

app/views/facturas_despacho/_form.html.erb
<%= simple_form_for(@factura_despacho) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :pedido %>
    <%= f.input :numero_de_factura %>
    <%= f.input :cancelada %>
    <%= f.input :estado %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/facturas_despacho/_remision.html.erb
<tr>
  <td><%= f.input :numero_de_remision %></td>
  <td class="ocultar_fecha"><%= f.text_field:fecha_de_despacho, class:"my_fecha" %></td>
  <td>
    <div class="">
      <label for="">Fecha De Despacho</label>
      <div class="input-group" >
        <input type="text" data-date-format="yyyy/mm/dd" class="form-control fecha"
        data-provide='datepicker' placeholder="Fecha"
        aria-describedby="basic-addon2" id='fecha'>
        <span class="input-group-addon " id="basic-addon2"> <i class="ion-calendar"></i> </span>
      </div>
    </div>
  </td>
  <td><%= f.input :cantidad_enviada %></td>
  <td><%= f.input :precio_a_facturar %></td>

  <td>
    <%= f.input_field :_destroy, as: :hidden %>
    <%= link_to '<button type="button" class="btn btn-outline-danger"><span><i class="ion-trash-a"></i></span></button>'.html_safe, '#', class: 'remove_remisiones' %>
  </td>
  <td><div class="form-actions">
    <%= f.button :submit, remote: true %>
  </div></td>
</tr>

app/views/facturas_despacho/create.js.erb
toastr.error('Cread0')

$('#contenedorFacturas').append("<%= j render @factura_despacho%>")

app/views/facturas_despacho/destroy.js.erb
toastr.error('Destruido')

$(<%="factura_#{@factura_despacho.id}"%>).remove()

app/views/facturas_despacho/edit.js.erb
toastr.error('editar')
$(<%="factura_#{@factura_despacho.id}"%>).remove()
$(<%="contenedor_#{@factura_despacho.id}"%>).append("<%= j render @factura_despacho%>")

app/views/facturas_despacho/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Facturas Despacho</h1>

<table>
  <thead>
    <tr>
      <th>Pedido</th>
      <th>Numero de factura</th>
      <th>Cancelada</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facturas_despacho.each do |factura_despacho| %>
      <tr>
        <td><%= factura_despacho.pedido %></td>
        <td><%= factura_despacho.numero_de_factura %></td>
        <td><%= factura_despacho.cancelada %></td>
        <td><%= factura_despacho.estado %></td>
        <td><%= link_to 'Show', factura_despacho %></td>
        <td><%= link_to 'Edit', edit_factura_despacho_path(factura_despacho) %></td>
        <td><%= link_to 'Destroy', factura_despacho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Factura Despacho', new_factura_despacho_path %>

app/views/facturas_despacho/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pedido:</strong>
  <%= @factura_despacho.pedido %>
</p>

<p>
  <strong>Numero de factura:</strong>
  <%= @factura_despacho.numero_de_factura %>
</p>

<p>
  <strong>Cancelada:</strong>
  <%= @factura_despacho.cancelada %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @factura_despacho.estado %>
</p>

<%= link_to 'Edit', edit_factura_despacho_path(@factura_despacho) %> |
<%= link_to 'Back', facturas_despacho_path %>

app/views/facturas_despacho/update.js.erb
toastr.error('Edicion Correcta')
toastr.error(<%="factura_#{@factura_despacho.id}"%>)
$(<%="factura_#{@factura_despacho.id}"%>).remove()
$(<%="contenedor_#{@factura_despacho.id}"%>).append("<%= j render @factura_despacho%>")